services:
  db-inventory:
    container_name: db-inventory
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: lfs
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventory
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431
  db-order:
    container_name: db-order
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order
      MYSQL_USER: lfs
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
  db-product:
    container_name: db-product
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: lfs
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432
### Postgres database for Keycloak
  db-keycloak:
    container_name: db-keycloak
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: lfs
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433
### Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: keycloak
      DB_PORT: 5433
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_USER: lfs
      DB_PASSWORD: root
      KC_HTTP_PORT: 8181

###zookeeper
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000

###kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOGG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1